name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Pull repositorio
        uses: actions/checkout@v4

      - name: Ejecutar tests
        run: docker build --target test --tag taskapp:test .

  build:
    runs-on: ubuntu-24.04
    needs: test
    if: github.event_name == 'push'
    steps:
      - name: Pull repositorio
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build --target production --tag ${{ secrets.DOCKER_HUB_USER }}/taskapp:latest .

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Subir imagen Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/taskapp:latest
